### ISSUE TITLE
repetitive code that needs to be refactored

### ISSUE THREAD

**Issue by shiryz** [WebAhead6/movphy#11]
You have a few lines that can be extracted and then written in a variable or value

e.g.

https://github.com/WebAhead6/movphy/blob/master/index.js#L46-L49

https://github.com/WebAhead6/movphy/blob/master/index.js#L53-L55

**Comment by MorisR** [comment]
here as well

https://github.com/WebAhead6/movphy/blob/master/style.css#L43-L52
https://github.com/WebAhead6/movphy/blob/master/style.css#L115-L124
