### ISSUE TITLE
Site is functional, but..

### ISSUE THREAD

**Issue by baderfahoum17** [WebAhead6/movphy#15]
the css is barebones, almost no styling went in
the project is supposed to use two api which it does, 

but what value are we getting from those two apis if the site is so minimal with little interactiveness?
more thought and styling should go into the website, those part take a lot of time and you should get used to that hardwork with deadlines, the api usage is fairly straight forward 
also for future occasions 
saving fields that are related to the same result should go into the same object
` Overview.textContent =  json.results[0].overview;
        VoteAverage.textContent = json.results[0].vote_average;
        ReleaseDate.textContent = json.results[0].release_date;`
should be
` let resultObject = { Overview: json.results[0].overview,
        VoteAverage : json.results[0].vote_average,
        ReleaseDate.textContent : json.results[0].release_date,
}
`
line 54 index.js
then extract the values

kudos on the functionality though

**Comment by mervatyo** [comment]
good to know
